apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 5
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          image: fragus/greeter
          ports:
            - containerPort: 3000