apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: greeter
  ports:
    - protocol: "TCP"
      port: 3000 # port accessible inside cluster
      targetPort: 3000 # Port to forward to inside the pod
      nodePort: 30001 # Port accessible outside cluster
  type: LoadBalancer

